version: "2"
services:
  unifi_exporter:
    image: b3vis/unifi_exporter
    restart: always
    container_name: unifi_exporter
    environment:
      - ARGUMENTS="-unifi.addr https://10.0.0.1:8443 -unifi.username admin -unifi.password password"
    ports:
      - "9130:9130"
